set(STACK_USE_SANITIZER OFF CACHE BOOL "Turn on/off thread sanitizer for current compiler")

if (CMAKE_BUILD_TYPE MATCHES Debug)
    if (STACK_USE_SANITIZER)
        if (CMAKE_CXX_COMPILER_ID MATCHES Clang OR CMAKE_CXX_COMPILER_ID MATCHES AppleClang)
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=thread")
            set(CMAKE_LINKER_FLAGS_DEBUG "${CMAKE_LINKER_FLAGS_DEBUG} -fsanitize=thread")
        elseif (CMAKE_CXX_COMPILER_ID MATCHES GNU)
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fsanitize=thread")
            set(CMAKE_LINKER_FLAGS_DEBUG "${CMAKE_LINKER_FLAGS_DEBUG} -fsanitize=thread")
        else()
            message("No flags are set for given compiler (${CMAKE_CXX_COMPILER_ID})")
        endif()
    else()
        message(STATUS "Compiling without sanitizer")
    endif()
endif()